### ISSUE TITLE
Change .current_limit_absolute not working - Solved, need to use different datapoint.

### ISSUE THREAD

**Issue by SirFlour** [o0shojo0o/ioBroker.opendtu#45]
**Describe the bug**  
I want to set the Watt from 600 to 500 via iObroker and it is not reflected in the opendtu. When i change it in the opendtu webpage it works

**To Reproduce**  
1. Go to Objectes in iobroker
2. Click on OpenDTU.current_limit_absolute  and change value from 600 to 500
3. Value changes to 500 and then back to 600
4. Also got an info in the protocol that value got written. not other infos in the protocoll

**Expected behavior**  
That the watt changes to 500

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: v0.1.4
 - JS-Controller version: 4.0.24 
 - Node version: <node-version> 
 - Operating system: Raspi4 - Docker ioBroker

**Additional context**  

What do i do wrong? If more infos and testing are helpful, i am happy to provide them :)

**Comment by o0shojo0o** [comment]
This is also a read-only data point, which is why there is also a lock on it and it must also be in expert mode in order to write a value in there.
I am therefore puzzled as to why anyone would want to write anything in there.

These are the data points that should interest you: 

<img width="1202" alt="image" src="https://user-images.githubusercontent.com/19333515/236687702-95ccd78e-d3ad-4a7d-a17b-ce8faa9a8faf.png">

**Comment by o0shojo0o** [comment]
The function is error free, I assume that your password is not set correctly in the adapter.
The password is needed for this control.

**Comment by SirFlour** [comment]
@o0shojo0o thanks a lot! indeed i tired to change the read only value and now i see i have to use the other values. It worked perfectly. 

Many thanks for your great & fast support and sorry for my mistake.

![grafik](https://user-images.githubusercontent.com/52317499/236891916-5a4cf385-afac-44ea-937a-385141104116.png)
