### ISSUE TITLE
openDTU adapter does not report Battery data when connecting to openDTU onbattery

### ISSUE THREAD

**Issue by cnitschkowski** [o0shojo0o/ioBroker.opendtu#51]
**Describe the bug**  
It is not a bug but a feature request.
I use openDTU onbattery (https://github.com/helgeerbe/OpenDTU-OnBattery) on my ESP32 which, in addition to the inverter related data, also has MQTT data points to report about status infos of the connected Victron Energy charging controller.
Would it be possible to include that data in this adapter, too?
They are reported using MQTT and a simple REST interface.

**Versions:**  
 - Adapter version: 0.15

**Comment by o0shojo0o** [comment]
Hi, 
I don't think so, for the following reasons:
1. the two projects Orignial and Custom OpenDTU could always be out of sync so that I would always have to keep an eye on both versions and if necessary build workarounds for the two different versions.
2. In my opinion, this would be an additional adapter for Victron with which the data could be fetched in IoBroker.
